name: Sync Upstream Dictionarry (stable)
on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: stable

      - name: Merge Dictionarry stable
        uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: stable
          upstream: Dictionarry-Hub/profilarr
          upstream-branch: stable
